### ISSUE TITLE
[chore] Create CI/CD with Github Actions

### ISSUE THREAD

**Issue by salomax** [Invistus/invistus#2]
As a developer,
  I want to have a streamlined and secure CI/CD pipeline,
  So that I can deploy branches to different environments and manage releases efficiently using GitHub Actions and AWS integration.

###  Background:
    Given the GitHub repository is configured with the AWS OIDC identity provider
    And an IAM role with the necessary permissions is created in AWS

###  Scenario: Deploy a Branch to Development Environment
    Given a new branch is pushed to the repository
    When the branch matches the pattern 'feature/*'
    Then the GitHub Actions workflow triggers
    And the workflow assumes the specified IAM role using AWS OIDC
    And the workflow deploys the branch to the development environment using the CloudFormation YAML file
    And I can validate the package in the AWS development environment

###  Scenario: Approve Package and Push to Production
    Given the package is validated in the development environment
    When I approve the package
    Then the GitHub Actions workflow triggers for the 'master' branch
    And the workflow deploys the package to the production environment
    And a new release is created with a version tag in the main branch

**Comment by salomax** [comment]
## CI/CD Pipeline Setup Using GitHub Actions and AWS CloudFormation with Gitflow

### Step 1: Implement Gitflow Branching Strategy

Implement the Gitflow branching strategy in your repository. The commonly used branches in this strategy are:
- `feature/*` - For new features or improvements.
- `release/*` - For preparing new releases.
- `hotfix/*` - For urgent fixes.
- `master` - Holds the code of the latest stable release.
- `develop` - Branch where the latest developments are merged into.

### Step 2: Set Up GitHub Actions Workflows

Create separate GitHub Actions workflows for deploying to development, staging, and production environments. These workflows should be stored in the `.github/workflows` directory in your repository.

### Step 3: Development Environment Deployment

#### Development Environment Workflow
- **Trigger**: Configured to activate on push events to `feature/*` branches.
- **Job Steps**:
  1. **Checkout Code**: Use the `actions/checkout` action to check out the code from the current branch.
  2. **Setup AWS CLI**: Configure AWS CLI using `aws-actions/configure-aws-cli` action.
  3. **Deploy to AWS**: Create a step to deploy the application to a development environment on AWS using a CloudFormation YAML file.

### Step 4: Staging Environment Deployment for Release

#### Staging Environment Workflow
- **Trigger**: Configured to activate on the creation of `release/*` branches.
- **Job Steps**: Similar to the Development Environment Workflow, but the deployment is to a staging environment which mirrors the production environment for testing and validation.

### Step 5: Package Validation and Approval

#### Package Validation
- Implement steps to validate the package on AWS, either through integration tests or other validation processes in the staging environment.

#### Approval Process
- After validation in the staging environment, initiate a manual approval step.
- Upon approval, create a pull request to merge the changes from the `release/*` branch to the `master` branch.

### Step 6: Production Deployment

#### Production Deployment Workflow
- **Trigger**: Configured to activate on push events to the `master` branch (when a pull request is merged).
- **Job Steps**: Similar to the previous workflows, but now deploying to the production environment using the CloudFormation YAML file.

### Step 7: Versioning and Release Tagging

#### Versioning and Release Tagging
- After a successful deployment to production, automatically create a new release tag using `gh` CLI or GitHub API.
- Document the changes in release notes and maintain a changelog within the repository.

## Github Actions Yaml file structure

```
name: CI/CD Pipeline with Gitflow

on:
  push:
    branches:
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
      - 'master'
      - 'develop'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-cli@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Development
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: |
          # Your deployment script for the development environment here.
          # You can use AWS CLI commands to deploy using CloudFormation YAML file.

      - name: Deploy to Staging
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          # Your deployment script for the staging environment here.

      - name: Deploy to Production
        if: github.ref == 'refs/heads/master'
        run: |
          # Your deployment script for the production environment here.

      - name: Tag Release
        if: github.ref == 'refs/heads/master'
        run: |
          # Your script to create a new release tag here. You might use `gh` CLI or GitHub API.
```

## Using AWS IAM Roles for GitHub Actions

To use IAM roles in GitHub Actions, you might opt to use an IAM role with specific permissions and assume this role in your GitHub Actions workflows.

[AWS documentation](https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/)

### Step 1: Create an IAM OIDC identity provider and role
1. Open the IAM console in AWS.
2. In the navigation pane, choose "Identity providers", and then choose "Create provider".
3. For the provider type, choose "OpenID Connect".
4. For the URL, enter https://token.actions.githubusercontent.com (the GitHub Actions OIDC provider).
5. For the audience, enter "sts.amazonaws.com".
6. Choose "Next Step", and then choose "Create".
7. Create a new IAM role for OIDC identity provider that you created.
8. Choose "Trust relationships", and then choose "Edit trust relationship".
9.Add a condition to the trust policy to check the sub claim in the incoming identity token, as shown in the blog post.

### Step 2: Create a GitHub Actions workflow

In your .github/workflows directory, create a new YAML file for your workflow. Here’s a snippet from the blog that demonstrates how to configure the aws-actions/configure-aws-credentials action to assume a role:

```
name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: my-ecr-repo
  K8S_NAMESPACE: my-k8s-namespace
  APP_NAME: my-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
        role-duration-seconds: 1200
        role-session-name: GitHubActions

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # ... the rest of your job steps here
```
In this YAML file:

The aws-actions/configure-aws-credentials action is used to assume the role created in AWS.
Replace 123456789012 with your AWS account ID and my-github-actions-role with the actual name of the IAM role you created.
role-session-name is set to "GitHubActions", but you can name it anything meaningful to you.
This setup leverages the OIDC provider to securely grant your GitHub Actions the necessary permissions to interact with AWS, without having to store AWS IAM user credentials as secrets in GitHub.

Remember to replace placeholders with your actual AWS account ID, role name, region, repository name, etc., and to add the necessary permissions to the IAM role to allow it to interact with AWS services as required by your workflow.
